version: '3'
services:
  generate:
    build:
      context: .
      dockerfile: ./Dockerfile.CovidAPI
    container_name: covidapi-generate
    tty: true
    stdin_open: true
    volumes:
      - static:/app/apps/covid-api/public
    working_dir: /app
    restart: always
    command: yarn workspace covid-api start
    network_mode: webproxy
  serve:
    image: covid-api_generate:latest
    env_file:
      - .env
    container_name: covidapi-serve
    tty: true
    stdin_open: true
    volumes:
      - static:/app/apps/covid-api/public
    working_dir: /app
    restart: always
    command: yarn workspace covid-api static
    expose:
      - 3100
    network_mode: webproxy
networks:
  default:
    external:
      name: webproxy
volumes:
   static: