From mhart/alpine-node:10

ENV PORT=3100
ENV NODE_ENV=production

RUN mkdir -p /var/www/app && \
    mkdir -p /var/www/app/node_modules

# Use app directory as current workdir
WORKDIR /var/www/app
ENV PATH /var/www/app/node_modules/.bin:$PATH
# Copy package.json to workdir
COPY package.json /var/www/app/
COPY yarn.lock /var/www/app/
COPY lerna.json /var/www/app/

COPY ./apps/covid-api /var/www/app/apps/covid-api/
RUN mkdir -p /var/www/app/apps/covid-api/public/
RUN touch /var/www/app/apps/covid-api/public/covid19_US_CA_County.json

RUN npx lerna bootstrap
Run yarn fix-packages

Run yarn workspace covid-api build

# Expose Port
EXPOSE $PORT
